### ISSUE TITLE
update_check returning None

### ISSUE THREAD

**Issue by rhiever** [bboe/update_checker#6]
I'm trying to use `update_check` in my project to notify users when they're running an out-of-date version, but it always returns `None`. Is there any additional setup that I need to perform?

**Comment by bboe** [comment]
What's the package/module name? I had a ton of spam projects that I didn't want to log so I implemented a whitelist (https://github.com/bboe/update_checker_app/blob/64cdf6cc81f6256faeafc0f19d46c3d4955c3677/update_checker_app/controllers.py#L8). If you want to make a pull request to that app with your packages, I'm happy to have them included.

Alternatively you can run your own version of the app by passing a different URL to https://github.com/bboe/update_checker/blob/4e6958984bab0fa7d3077434383f408171b77e68/update_checker.py#L109

**Comment by rhiever** [comment]
https://github.com/bboe/update_checker_app/pull/2 :+1:

**Comment by bboe** [comment]
Merged and updated the app. Please confirm.

**Comment by rhiever** [comment]
Looks like it's working now. Cheers! :-)
