### ISSUE TITLE
update_checker compares versions based on strings, not numbers

### ISSUE THREAD

**Issue by rhiever** [bboe/update_checker#9]
Ran into an issue today where I rolled out v0.2.10 and update_checker wasn't pinging me to update from v0.2.9. Turns out update_checker performs the update comparisons based on strings, and in Python '0.2.9' > '0.2.10'.

Would be nice to have this bug fixed -- comparisons should be performed based on the number.

**Comment by bboe** [comment]
I'd be surprised if it's based on strings. Are you sure about that? It could be that the results are cached.

**Comment by rhiever** [comment]
Huh, weird. Must've been a caching issue.

**Comment by bboe** [comment]
The cache persists for about an hour.
